// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpointer_basic.h"

extern XPointer_basic_Config XPointer_basic_ConfigTable[];

XPointer_basic_Config *XPointer_basic_LookupConfig(u16 DeviceId) {
	XPointer_basic_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPOINTER_BASIC_NUM_INSTANCES; Index++) {
		if (XPointer_basic_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPointer_basic_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPointer_basic_Initialize(XPointer_basic *InstancePtr, u16 DeviceId) {
	XPointer_basic_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPointer_basic_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPointer_basic_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

