// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _gcd_HH_
#define _gcd_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "gcd_gcd_bus_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_GCD_BUS_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_GCD_BUS_DATA_WIDTH = 32>
struct gcd : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_gcd_bus_AWVALID;
    sc_out< sc_logic > s_axi_gcd_bus_AWREADY;
    sc_in< sc_uint<C_S_AXI_GCD_BUS_ADDR_WIDTH> > s_axi_gcd_bus_AWADDR;
    sc_in< sc_logic > s_axi_gcd_bus_WVALID;
    sc_out< sc_logic > s_axi_gcd_bus_WREADY;
    sc_in< sc_uint<C_S_AXI_GCD_BUS_DATA_WIDTH> > s_axi_gcd_bus_WDATA;
    sc_in< sc_uint<C_S_AXI_GCD_BUS_DATA_WIDTH/8> > s_axi_gcd_bus_WSTRB;
    sc_in< sc_logic > s_axi_gcd_bus_ARVALID;
    sc_out< sc_logic > s_axi_gcd_bus_ARREADY;
    sc_in< sc_uint<C_S_AXI_GCD_BUS_ADDR_WIDTH> > s_axi_gcd_bus_ARADDR;
    sc_out< sc_logic > s_axi_gcd_bus_RVALID;
    sc_in< sc_logic > s_axi_gcd_bus_RREADY;
    sc_out< sc_uint<C_S_AXI_GCD_BUS_DATA_WIDTH> > s_axi_gcd_bus_RDATA;
    sc_out< sc_lv<2> > s_axi_gcd_bus_RRESP;
    sc_out< sc_logic > s_axi_gcd_bus_BVALID;
    sc_in< sc_logic > s_axi_gcd_bus_BREADY;
    sc_out< sc_lv<2> > s_axi_gcd_bus_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    gcd(sc_module_name name);
    SC_HAS_PROCESS(gcd);

    ~gcd();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    gcd_gcd_bus_s_axi<C_S_AXI_GCD_BUS_ADDR_WIDTH,C_S_AXI_GCD_BUS_DATA_WIDTH>* gcd_gcd_bus_s_axi_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<16> > a;
    sc_signal< sc_lv<16> > b;
    sc_signal< sc_logic > pResult_ap_vld;
    sc_signal< sc_lv<16> > b_read_reg_102;
    sc_signal< sc_lv<16> > a_read_reg_107;
    sc_signal< sc_lv<1> > tmp_3_fu_72_p2;
    sc_signal< sc_lv<1> > tmp_3_reg_115;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_2_fu_66_p2;
    sc_signal< sc_lv<16> > a_assign_fu_78_p2;
    sc_signal< sc_lv<16> > a_assign_reg_121;
    sc_signal< sc_lv<16> > b_assign_fu_84_p2;
    sc_signal< sc_lv<16> > b_assign_reg_126;
    sc_signal< sc_lv<16> > b_assign_1_fu_90_p3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<16> > a_assign_1_fu_96_p3;
    sc_signal< sc_lv<16> > p_s_reg_45;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<16> > result_reg_56;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_a_assign_1_fu_96_p3();
    void thread_a_assign_fu_78_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_b_assign_1_fu_90_p3();
    void thread_b_assign_fu_84_p2();
    void thread_pResult_ap_vld();
    void thread_tmp_2_fu_66_p2();
    void thread_tmp_3_fu_72_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
