// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpointer_basic.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPointer_basic_CfgInitialize(XPointer_basic *InstancePtr, XPointer_basic_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Pointer_basic_io_BaseAddress = ConfigPtr->Pointer_basic_io_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPointer_basic_Start(XPointer_basic *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL) & 0x80;
    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPointer_basic_IsDone(XPointer_basic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPointer_basic_IsIdle(XPointer_basic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPointer_basic_IsReady(XPointer_basic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPointer_basic_EnableAutoRestart(XPointer_basic *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL, 0x80);
}

void XPointer_basic_DisableAutoRestart(XPointer_basic *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL, 0);
}

void XPointer_basic_Set_d_i(XPointer_basic *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_D_I_DATA, Data);
}

u32 XPointer_basic_Get_d_i(XPointer_basic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_D_I_DATA);
    return Data;
}

u32 XPointer_basic_Get_d_o(XPointer_basic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_D_O_DATA);
    return Data;
}

u32 XPointer_basic_Get_d_o_vld(XPointer_basic *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_D_O_CTRL);
    return Data & 0x1;
}

void XPointer_basic_InterruptGlobalEnable(XPointer_basic *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_GIE, 1);
}

void XPointer_basic_InterruptGlobalDisable(XPointer_basic *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_GIE, 0);
}

void XPointer_basic_InterruptEnable(XPointer_basic *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_IER);
    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_IER, Register | Mask);
}

void XPointer_basic_InterruptDisable(XPointer_basic *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_IER);
    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_IER, Register & (~Mask));
}

void XPointer_basic_InterruptClear(XPointer_basic *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPointer_basic_WriteReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_ISR, Mask);
}

u32 XPointer_basic_InterruptGetEnabled(XPointer_basic *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_IER);
}

u32 XPointer_basic_InterruptGetStatus(XPointer_basic *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPointer_basic_ReadReg(InstancePtr->Pointer_basic_io_BaseAddress, XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_ISR);
}

