// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// pointer_basic_io
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of d_i
//        bit 31~0 - d_i[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of d_o
//        bit 31~0 - d_o[31:0] (Read)
// 0x1c : Control signal of d_o
//        bit 0  - d_o_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_AP_CTRL  0x00
#define XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_GIE      0x04
#define XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_IER      0x08
#define XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_ISR      0x0c
#define XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_D_I_DATA 0x10
#define XPOINTER_BASIC_POINTER_BASIC_IO_BITS_D_I_DATA 32
#define XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_D_O_DATA 0x18
#define XPOINTER_BASIC_POINTER_BASIC_IO_BITS_D_O_DATA 32
#define XPOINTER_BASIC_POINTER_BASIC_IO_ADDR_D_O_CTRL 0x1c

